fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    vcsrepo: "puppetlabs/vcsrepo"
    apt: "puppetlabs/apt"
    yumrepo: "puppetlabs/yumrepo_core"
    zypprepo: "puppet/zypprepo"
    systemd: "camptocamp/systemd"
    icinga: "icinga/icinga"
  symlinks:
    icingaweb2: "#{source_dir}"
